CREATE DATABASE usapp;

CREATE TABLE IF NOT EXISTS urlData (
   	url_id VARCHAR UNIQUE NOT NULL,
	original_url VARCHAR UNIQUE NOT NULL,
	short_url VARCHAR UNIQUE NOT NULL,
	created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
   	user_id INT GENERATED ALWAYS AS IDENTITY (START WITH 100001) PRIMARY KEY,
	first_name VARCHAR ( 50 ) NOT NULL,
	last_name VARCHAR ( 50 ) NOT NULL,
	email VARCHAR ( 100 ) UNIQUE NOT NULL,
	password VARCHAR ( 150 ) NOT NULL,
	api_key VARCHAR ( 50 ) NOT NULL,
	created_on TIMESTAMP NOT NULL
);